### ISSUE TITLE
Pachyderm not an option for label studio cloud storage

### ISSUE THREAD

**Issue by williamAddison** [pachyderm/examples#57]
This is strange because I saw pachyderm as an option for cloud storage just yesterday, not even 24 hours ago. I am running label studio on a python virtual environment like they recommend for Ubuntu users and this is the same way I accessed it yesterday. 

I am running a minikube cluster with port-forwarding for the pachyderm service and I had to open a separate terminal to connect to pachyderm. I have pachyderm connected to localhost:30650 and I can open the console in my browser to see my repositories. 

occasionally I see this output from the terminal running label-studio `[2023-06-01 13:56:01,768] [urllib3.connectionpool::urlopen::823] [WARNING] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)'))': /api/5820521/envelope/`

but I am still able to work with it in the browser. Any help is greatly appreciated.

**Comment by williamAddison** [comment]
I figured out that the problem was that I had not started a linked label-studio container as outline in this guide: https://docs.pachyderm.com/latest/integrate/label-studio/

I can see pachyderm as an option now to use as storage but when I try to link it to the source it gives an error of `Failed to start pachctl mount-server`. I will try to troubleshoot and leave this open in case someone else has a similar problem to this

**Comment by chainlink** [comment]
You're g2g, right @williamAddison ?

**Comment by williamAddison** [comment]
Yes I have solved the issue, this can be closed
